# Generated by Django 3.1.7 on 2021-09-01 18:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowMetrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('download_count', models.IntegerField(default=0)),
                ('frontend_traffic', models.IntegerField(default=0)),
                ('facebook_redirect_count', models.IntegerField(default=0)),
                ('twitter_redirect_count', models.IntegerField(default=0)),
                ('instagram_redirect_count', models.IntegerField(default=0)),
                ('tiktok_redirect_count', models.IntegerField(default=0)),
                ('youtube_redirect_count', models.IntegerField(default=0)),
                ('reddit_redirect_count', models.IntegerField(default=0)),
                ('show_fk', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='manage.show')),
            ],
        ),
        migrations.CreateModel(
            name='EpisodeMetrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('download_count', models.IntegerField(default=0)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('episode_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage.episode')),
            ],
        ),
    ]
